# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rz0Clos4KE125fImia_6WGd5UzgkpiX
"""

import numpy as np
import matplotlib.pyplot as plt
x1 = np.array([1, 1, 12, 12, 1])
y1 = np.array([1, 7, 7, 1, 1])
plt.plot(x1, y1, color="black")

x_red = np.array([1, 1, 12, 12, 1])
y_red = np.array([3, 7, 7, 4, 4])
plt.fill(x_red, y_red, color="red")
x_yellow = np.array([1, 1, 12, 12, 1])
y_yellow = np.array([1, 4,4, 1, 1])
plt.fill(x_yellow, y_yellow, color="yellow")

plt.gca().set_aspect('equal')
plt.axis('off')
plt.show()